name: Sync Figma Components to GitHub
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-figma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch and Sync Figma Components
        uses: jstrieb/figma-action@master
        with:
          figma-token: ${{ secrets.FIGMA_TOKEN }}
          file-key: ${{ secrets.FIGMA_FILE_KEY }}
          output-directory: 'maquettes'
